--- # Deploy

- include: deploy-remove-rollback.yml
- include: deploy-build.yml
- include: deploy-db.yml

# tag to trigger a unicorn restart
- name: reset
  # needs to do something here
  command: echo 1
  tags:
    - reset
    - skip_ansible_lint
  notify:
    - restart unicorn
